version: '3'
services:
  play-ts-app:
    image: play-ts-app:0.0.3
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ../config/config.json:/usr/share/nginx/html/config/config.json
      - ./videos:/app/videos
